name: Terraform Format Check

on:
  pull_request:
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform-fmt.yml'

jobs:
  terraform-fmt:
    name: Terraform Format
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform Format Check
        id: fmt
        run: terraform fmt -check -recursive
        continue-on-error: true

      - name: Terraform Format Result
        if: steps.fmt.outcome == 'failure'
        run: |
          echo "Terraform format check failed. Please run 'terraform fmt -recursive' to fix formatting issues."
          terraform fmt -diff -recursive
          exit 1
